name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
      
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
    
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
      
    #- name: Build the Docker image
      #run: docker buildx build --platform linux/arm/v6 --no-cache ./rtl_433

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ben-newman-0
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.GH_PACKAGES_PAT }}
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Docker repository to tag the image with
        repository: ben-newman-0/rtl_433-arm32v6
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        #tags: ${{ github.sha }}
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: false
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: true
        # Path to the build context
        path: ./rtl_433 # optional, default is .
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        #dockerfile: # optional
        # Sets the target stage to build
        #target: # optional
        # Always attempt to pull a newer version of the image
        #always_pull: # optional
        # Comma-delimited list of build-time variables
        #build_args: # optional
        # Comma-delimited list of images to consider as cache sources
        #cache_froms: # optional
        # Comma-delimited list of labels to add to the built image
        #labels: # optional
        # Adds labels with git repository information to the built image
        add_git_labels: true
        # Whether to push the image
        #push: # optional, default is true
